services:
  p4studio:
    build: .
    image: p4studio:1

    container_name: p4studio
    hostname: p4studio

    privileged: true

    entrypoint: tail -f /dev/null > /dev/null

    ports: 
      - 2222:22

    networks:
      - p4net
networks:
  p4net:
    name: p4net
